name: auto_game
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.4.0
  intl: ^0.19.0
  lottie: ^3.0.0
  get_it: ^7.6.7
  ftoast: ^2.0.0
  auto_route: ^8.0.3
  google_fonts: ^6.2.1
  pull_to_refresh: ^2.0.0
  auto_size_text: ^3.0.0
  flutter_riverpod: ^2.4.10
  connectivity_plus: ^6.0.2
  flutter_screenutil: ^5.9.0
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  flutter_native_splash: ^2.3.10
  json_view: ^0.4.2


  #firebase
  firebase_auth: ^4.17.6
  firebase_core: ^2.25.5
  cloud_firestore: ^4.15.6
  google_sign_in: ^6.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: ^2.4.7
  build_runner: ^2.4.8
  flutter_lints: ^4.0.0
  auto_route_generator: ^8.0.0
  flutter_launcher_icons: ^0.13.1

flutter:

  uses-material-design: true

flutter_native_splash:
  background_image: 'assets/png/splash.png'

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: 'assets/png/app_logo.png'

